version: "3.8"
services:
  postgresql:
    image: postgres:10.4
    ports:
      - "5433:5432"
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: cms
    networks:
      - comment

networks:
  comment:
    driver: bridge